spring.application.name=TitanFitnessClub

spring.datasource.url=jdbc:mysql://localhost:3306/titanfitnessclub
spring.datasource.username=root
spring.datasource.password=Rudra2811???

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080